services:
  symfony:
    container_name: leboncoin-eco-plus
    image: leboncoin-eco-plus
    build:
      context: ./leboncoin-eco-plus
      dockerfile: Dockerfile
    ports:
      - 8002:80
    volumes:
      - ./leboncoin-eco-plus:/var/www/

  # font-end:

  database:
    container_name: database
    image: mysql
    ports:
      -  3306:3306
    environment:
      MYSQL_DATABASE: leboncoin_eco_plus
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin